import type { PromptSpec } from "../schema/prompt-spec.js";

/**
 * Render a compact PR comment for GitHub.
 * Designed to be short, scannable, and useful.
 */
export function renderComment(spec: PromptSpec): string {
	const lines: string[] = [];

	lines.push("## PR Spec Analysis");
	lines.push("");
	lines.push(
		`**${spec.intent.change_type}** | ${spec.stats.files_changed} files | +${spec.stats.additions}/-${spec.stats.deletions}`,
	);
	lines.push("");

	// Summary
	lines.push("### Summary");
	lines.push(spec.intent.likely_goal);
	lines.push("");

	// Top affected files (max 10)
	lines.push(`### Affected Files (${spec.affected_files.length})`);
	const topFiles = spec.affected_files.slice(0, 10);
	for (const f of topFiles) {
		lines.push(`- \`${f.filename}\` (${f.status}, +${f.additions}/-${f.deletions})`);
	}
	if (spec.affected_files.length > 10) {
		lines.push(`- ... and ${spec.affected_files.length - 10} more`);
	}
	lines.push("");

	// Risk flags
	if (spec.risk_flags.length > 0) {
		lines.push("### Risk Flags");
		for (const r of spec.risk_flags.slice(0, 5)) {
			const icon = r.severity === "high" ? "🔴" : r.severity === "medium" ? "🟡" : "🟢";
			lines.push(`- ${icon} **${r.severity}**: ${r.description}`);
		}
		if (spec.risk_flags.length > 5) {
			lines.push(`- ... and ${spec.risk_flags.length - 5} more`);
		}
		lines.push("");
	}

	// Acceptance Criteria
	lines.push("### Acceptance Criteria");
	for (const c of spec.acceptance_criteria) {
		lines.push(`- [ ] ${c}`);
	}
	lines.push("");

	// Open Questions
	if (spec.open_questions.length > 0) {
		lines.push("### Open Questions");
		for (const q of spec.open_questions) {
			lines.push(`- ${q}`);
		}
		lines.push("");
	}

	// Copy-ready prompt block
	lines.push("<details>");
	lines.push("<summary>📋 Copy-ready prompt spec</summary>");
	lines.push("");
	lines.push("```");
	lines.push(spec.generation_prompt);
	lines.push("```");
	lines.push("</details>");
	lines.push("");

	lines.push("---");
	lines.push(
		`*Generated by [pr-to-spec](https://github.com/jeremylongshore/pr-to-spec) v${spec.version}*`,
	);

	return lines.join("\n");
}
