export { enhanceSpec, type AIEnhanceOptions } from "./core/ai/enhancer.js";
export { diffSpecs, type SpecDiff, type SectionDiff } from "./core/diff/spec-diff.js";
export { PromptSpecSchema, type PromptSpec, type FileChange } from "./core/schema/prompt-spec.js";
export { createClient, fetchPR, type PRData, type PRFile } from "./core/github/client.js";
export { generateSpec, generateSpecFromPR, compactSpec } from "./core/parsing/pr-parser.js";
export { parseReviews, type ReviewSummary } from "./core/parsing/review-parser.js";
export { analyzeSemanticDiff, type SemanticChange } from "./core/parsing/semantic-diff.js";
export { detectMonorepo, type MonorepoInfo } from "./core/parsing/monorepo-detector.js";
export { classifyRisks, type RiskFlag } from "./core/risk/classifier.js";
export { renderYaml } from "./core/rendering/yaml.js";
export { renderMarkdown } from "./core/rendering/markdown.js";
export { renderComment } from "./core/rendering/comment.js";
export { renderJson } from "./core/rendering/json.js";
export { githubPRtoDiffSource } from "./core/sources/github.js";
export { buildLocalDiffSource, parseDiffStat, parseNameStatus } from "./core/sources/local.js";
export type { DiffSource, DiffFile } from "./core/sources/types.js";
export { IntentSchema, type Intent } from "./core/intent/schema.js";
export { readIntent, writeIntent } from "./core/intent/storage.js";
